apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-rhel9-vm
  labels:
    app.kubernetes.io/name: test-rhel9-vm
spec:
  running: false # Starting as 'false' for safety, will be changed in overlays if needed
  template:
    metadata:
      labels:
        kubevirt.io/os: rhel9
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              model: virtio
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: "registry.redhat.io/rhel9/rhel-guest-image" # Uses the official RHEL9 image
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: test-rhel9-vm2
              users:
                - name: cloud-user
                  ssh_authorized_keys:
                     - ssh-rsa *****
